// Generated by tableauc 0.1.1. DO NOT EDIT.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: hero__test_conf.proto

package excel

import (
	_ "github.com/Wenchy/tableau/proto/tableaupb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Hero struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RewardMap map[uint32]*Hero_Reward `protobuf:"bytes,1,rep,name=reward_map,json=rewardMap,proto3" json:"reward_map,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Hero) Reset() {
	*x = Hero{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hero__test_conf_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hero) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hero) ProtoMessage() {}

func (x *Hero) ProtoReflect() protoreflect.Message {
	mi := &file_hero__test_conf_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hero.ProtoReflect.Descriptor instead.
func (*Hero) Descriptor() ([]byte, []int) {
	return file_hero__test_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Hero) GetRewardMap() map[uint32]*Hero_Reward {
	if x != nil {
		return x.RewardMap
	}
	return nil
}

type Hero_Reward struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Desc string `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
}

func (x *Hero_Reward) Reset() {
	*x = Hero_Reward{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hero__test_conf_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hero_Reward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hero_Reward) ProtoMessage() {}

func (x *Hero_Reward) ProtoReflect() protoreflect.Message {
	mi := &file_hero__test_conf_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hero_Reward.ProtoReflect.Descriptor instead.
func (*Hero_Reward) Descriptor() ([]byte, []int) {
	return file_hero__test_conf_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Hero_Reward) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Hero_Reward) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

var File_hero__test_conf_proto protoreflect.FileDescriptor

var file_hero__test_conf_proto_rawDesc = []byte{
	0x0a, 0x15, 0x68, 0x65, 0x72, 0x6f, 0x5f, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x63, 0x6f, 0x6e,
	0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x74, 0x65, 0x73, 0x74, 0x65, 0x78, 0x63,
	0x65, 0x6c, 0x1a, 0x1e, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x61, 0x75, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x61, 0x75, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x83, 0x02, 0x0a, 0x04, 0x48, 0x65, 0x72, 0x6f, 0x12, 0x49, 0x0a, 0x0a, 0x72,
	0x65, 0x77, 0x61, 0x72, 0x64, 0x5f, 0x6d, 0x61, 0x70, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1e, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x65, 0x78, 0x63, 0x65, 0x6c, 0x2e, 0x48, 0x65, 0x72, 0x6f,
	0x2e, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x42,
	0x0a, 0x82, 0xb5, 0x18, 0x06, 0x22, 0x02, 0x49, 0x44, 0x28, 0x01, 0x52, 0x09, 0x72, 0x65, 0x77,
	0x61, 0x72, 0x64, 0x4d, 0x61, 0x70, 0x1a, 0x54, 0x0a, 0x0e, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64,
	0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2c, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x74, 0x65, 0x73, 0x74,
	0x65, 0x78, 0x63, 0x65, 0x6c, 0x2e, 0x48, 0x65, 0x72, 0x6f, 0x2e, 0x52, 0x65, 0x77, 0x61, 0x72,
	0x64, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x42, 0x0a, 0x06,
	0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x12, 0x18, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x42, 0x08, 0x82, 0xb5, 0x18, 0x04, 0x0a, 0x02, 0x49, 0x44, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x1e, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0a,
	0x82, 0xb5, 0x18, 0x06, 0x0a, 0x04, 0x44, 0x65, 0x73, 0x63, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63,
	0x3a, 0x16, 0x82, 0xb5, 0x18, 0x12, 0x0a, 0x04, 0x48, 0x65, 0x72, 0x6f, 0x10, 0x01, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x05, 0x40, 0x01, 0x48, 0x01, 0x42, 0x45, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x57, 0x65, 0x6e, 0x63, 0x68, 0x79, 0x2f, 0x74, 0x61,
	0x62, 0x6c, 0x65, 0x61, 0x75, 0x2f, 0x63, 0x6d, 0x64, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x74,
	0x65, 0x73, 0x74, 0x70, 0x62, 0x2f, 0x65, 0x78, 0x63, 0x65, 0x6c, 0x82, 0xb5, 0x18, 0x10, 0x0a,
	0x0e, 0x68, 0x65, 0x72, 0x6f, 0x2f, 0x54, 0x65, 0x73, 0x74, 0x2e, 0x78, 0x6c, 0x73, 0x78, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hero__test_conf_proto_rawDescOnce sync.Once
	file_hero__test_conf_proto_rawDescData = file_hero__test_conf_proto_rawDesc
)

func file_hero__test_conf_proto_rawDescGZIP() []byte {
	file_hero__test_conf_proto_rawDescOnce.Do(func() {
		file_hero__test_conf_proto_rawDescData = protoimpl.X.CompressGZIP(file_hero__test_conf_proto_rawDescData)
	})
	return file_hero__test_conf_proto_rawDescData
}

var file_hero__test_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_hero__test_conf_proto_goTypes = []interface{}{
	(*Hero)(nil),        // 0: testexcel.Hero
	nil,                 // 1: testexcel.Hero.RewardMapEntry
	(*Hero_Reward)(nil), // 2: testexcel.Hero.Reward
}
var file_hero__test_conf_proto_depIdxs = []int32{
	1, // 0: testexcel.Hero.reward_map:type_name -> testexcel.Hero.RewardMapEntry
	2, // 1: testexcel.Hero.RewardMapEntry.value:type_name -> testexcel.Hero.Reward
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_hero__test_conf_proto_init() }
func file_hero__test_conf_proto_init() {
	if File_hero__test_conf_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hero__test_conf_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hero); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hero__test_conf_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hero_Reward); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hero__test_conf_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hero__test_conf_proto_goTypes,
		DependencyIndexes: file_hero__test_conf_proto_depIdxs,
		MessageInfos:      file_hero__test_conf_proto_msgTypes,
	}.Build()
	File_hero__test_conf_proto = out.File
	file_hero__test_conf_proto_rawDesc = nil
	file_hero__test_conf_proto_goTypes = nil
	file_hero__test_conf_proto_depIdxs = nil
}
